# Generated by Django 3.1.3 on 2020-11-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(default='student', max_length=20, verbose_name='role'),
        ),
    ]
