# Generated by Django 3.1.3 on 2020-11-12 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('student_id', models.IntegerField(unique=True)),
                ('mobile_number', models.CharField(default='09100000000', max_length=11)),
                ('password', models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(6)])),
            ],
        ),
    ]
