# Generated by Django 3.1.2 on 2020-10-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUniversity', '0007_auto_20201026_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
