# Generated by Django 3.1.2 on 2020-10-29 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyUniversity', '0010_auto_20201028_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.AutoField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=30, unique=True)),
                ('university_domain', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.BigIntegerField(default=9100000000),
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyUniversity.university'),
        ),
    ]
