# Generated by Django 3.1.2 on 2020-10-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUniversity', '0011_auto_20201029_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='university_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
    ]
