# Generated by Django 3.1.2 on 2020-10-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUniversity', '0012_auto_20201029_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='university',
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
