# Generated by Django 3.1.2 on 2020-10-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUniversity', '0013_auto_20201029_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='09100000000', max_length=11),
        ),
    ]
