# Generated by Django 3.1.3 on 2020-12-23 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BookBSE', '0002_auto_20201206_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('academic_rank', models.CharField(choices=[('Professor', 'استاد'), ('Associate Professor', 'دانشیار'), ('Assistant Professor', 'استادیار')], max_length=20)),
                ('direct_telephone', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(max_length=50)),
                ('research_axes', models.TextField(blank=True)),
                ('bachelor', models.CharField(blank=True, max_length=200)),
                ('masters', models.CharField(blank=True, max_length=200)),
                ('phd', models.CharField(blank=True, max_length=200)),
                ('postdoctoral', models.CharField(blank=True, max_length=200)),
                ('webpage_link', models.CharField(blank=True, max_length=100)),
                ('google_scholar_link', models.CharField(blank=True, max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookBSE.faculty')),
            ],
        ),
    ]
