# Generated by Django 3.1.3 on 2020-12-30 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BookBSE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('time_id', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.CharField(choices=[('Saturday', 'شنبه'), ('Sunday', 'یکشنبه'), ('Monday', 'دوشنبه'), ('Tuesday', 'سه\u200cشنبه'), ('Wednesday', 'چهارشنبه'), ('Thursday', 'پنج\u200cشنبه'), ('Friday', 'جمعه')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ResearchAxis',
            fields=[
                ('research_axis_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookBSE.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='professors/images/')),
                ('academic_rank', models.CharField(choices=[('Professor', 'استاد'), ('Associate Professor', 'دانشیار'), ('Assistant Professor', 'استادیار')], max_length=20)),
                ('direct_telephone', models.CharField(blank=True, max_length=11)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('bachelor', models.CharField(blank=True, max_length=200)),
                ('masters', models.CharField(blank=True, max_length=200)),
                ('phd', models.CharField(blank=True, max_length=200)),
                ('postdoctoral', models.CharField(blank=True, max_length=200)),
                ('webpage_link', models.CharField(blank=True, max_length=100)),
                ('google_scholar_link', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookBSE.faculty')),
                ('free_times', models.ManyToManyField(blank=True, to='professors.Time')),
                ('research_axes', models.ManyToManyField(blank=True, to='professors.ResearchAxis')),
            ],
        ),
    ]
