# Generated by Django 3.1.3 on 2020-12-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='image',
            field=models.ImageField(blank=True, upload_to='professors/images/'),
        ),
    ]
