# Generated by Django 3.1.3 on 2020-12-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_professor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
