# Generated by Django 3.1.3 on 2020-12-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_professor_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchAxis',
            fields=[
                ('researchaxis_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='professor',
            name='research_axes',
        ),
        migrations.AddField(
            model_name='professor',
            name='research_axes',
            field=models.ManyToManyField(blank=True, to='professors.ResearchAxis'),
        ),
    ]
