# Generated by Django 3.1.3 on 2020-12-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0005_auto_20201223_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='free_times',
            field=models.ManyToManyField(blank=True, to='professors.Times'),
        ),
    ]
