# Generated by Django 3.1.2 on 2020-11-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='users',
            new_name='user',
        ),
    ]
