# Generated by Django 3.1.2 on 2020-12-01 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('established_year', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('head_of_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='event/images/')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('hold_type', models.CharField(choices=[('Presence', 'Presence'), ('Online', 'Online')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('cost', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.organization')),
            ],
        ),
    ]
