# Generated by Django 3.1.3 on 2020-12-11 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BookBSE', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureDeputy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookBSE.faculty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('established_year', models.IntegerField(blank=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('culture_deputy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.culturedeputy')),
                ('head_of_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventAuthorizedOrganizer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('culture_deputy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.culturedeputy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='event/images/')),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('hold_type', models.CharField(choices=[('Presence', 'حضوری'), ('Online', 'آنلاین')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('cost', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=100)),
                ('remaining_capacity', models.IntegerField(default=100)),
                ('verified', models.BooleanField(default=False)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.organization')),
            ],
        ),
    ]
