# Generated by Django 3.1.3 on 2020-12-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='remaining_capacity',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='hold_type',
            field=models.CharField(choices=[('Presence', 'حضوری'), ('Online', 'آنلاین')], max_length=10),
        ),
        migrations.AlterField(
            model_name='organization',
            name='established_year',
            field=models.IntegerField(blank=True),
        ),
    ]
