# Generated by Django 3.1.2 on 2020-11-27 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, null=True)),
                ('state', models.BooleanField(default=False)),
                ('trade', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=1024, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookBSE.book')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('book', 'seller', 'buyer')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.IntegerField()),
                ('printno', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=1024, null=True)),
                ('upload', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookBSE.book')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('accused', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accused', to=settings.AUTH_USER_MODEL)),
                ('accuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuser', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookBSE.trade')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookBSE.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookBSE.faculty'),
        ),
        migrations.AddField(
            model_name='book',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookBSE.field'),
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookId', models.IntegerField(default=0)),
                ('stock_id', models.IntegerField()),
                ('imageUrl', models.URLField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookBSE.book')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DemandClient', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DemandSeller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('book', 'seller', 'client')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'author', 'publisher')},
        ),
    ]
