# Generated by Django 3.1.3 on 2021-01-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBSE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='image',
            field=models.ImageField(blank=True, upload_to='faculty/images/'),
        ),
    ]
