# Generated by Django 3.1.2 on 2020-11-12 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookBSE', '0003_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookBSE.faculty')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookBSE.field')),
            ],
            options={
                'unique_together': {('name', 'author', 'publisher')},
            },
        ),
    ]
