# Generated by Django 3.1.2 on 2020-11-12 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookBSE', '0005_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.IntegerField()),
                ('printno', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField()),
                ('upload', models.DateTimeField()),
                ('update', models.DateTimeField()),
                ('reserve', models.DateTimeField(auto_now_add=True)),
                ('trade', models.DateTimeField()),
                ('state', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookBSE.book')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('book', 'seller', 'buyer')},
            },
        ),
    ]
