# Generated by Django 3.1.2 on 2020-11-12 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookBSE', '0006_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookBSE.book')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DemandClient', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DemandSeller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('book', 'seller', 'client')},
            },
        ),
    ]
