# Generated by Django 3.1.2 on 2020-11-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBSE', '0008_auto_20201113_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
