# Generated by Django 3.1.2 on 2020-11-14 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookBSE', '0009_auto_20201114_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('accused', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accused', to=settings.AUTH_USER_MODEL)),
                ('accuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuser', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookBSE.trade')),
            ],
        ),
    ]
