# Generated by Django 3.1.2 on 2020-11-14 20:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookBSE', '0010_reportproblem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportproblem',
            unique_together={('accuser', 'accused', 'trade')},
        ),
    ]
