# Generated by Django 3.1.2 on 2020-11-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBSE', '0011_auto_20201115_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade',
            field=models.DateTimeField(blank=True),
        ),
    ]
