# Generated by Django 3.1.2 on 2020-11-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBSE', '0012_auto_20201115_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
