# Generated by Django 3.1.2 on 2020-11-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBSE', '0013_auto_20201115_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
