# Generated by Django 3.1.3 on 2020-11-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBSE', '0014_auto_20201115_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
