# Generated by Django 3.1.3 on 2020-11-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBSE', '0015_demand_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='image',
        ),
        migrations.AddField(
            model_name='demand',
            name='imageUrl',
            field=models.URLField(blank=True),
        ),
    ]
