# Generated by Django 3.1.3 on 2020-11-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBSE', '0016_auto_20201123_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
