# Generated by Django 3.1.3 on 2020-11-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBSE', '0017_auto_20201123_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='printno',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='reserve',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='trade',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='update',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='upload',
        ),
        migrations.AlterField(
            model_name='trade',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
