# Generated by Django 3.1.3 on 2020-11-23 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BookBSE', '0018_auto_20201123_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='stockId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='edition',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='printno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='reserve',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='trade',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='update',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='upload',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
