# Generated by Django 3.1.3 on 2020-11-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookBSE', '0019_auto_20201123_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='stockId',
        ),
    ]
