# Generated by Django 3.1.3 on 2020-11-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBSE', '0021_auto_20201123_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='price',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
    ]
