# Generated by Django 3.1.3 on 2020-11-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBSE', '0022_auto_20201123_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
