# Generated by Django 3.1.3 on 2020-11-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBSE', '0023_auto_20201123_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='stock_id',
            field=models.IntegerField(default=1),
        ),
    ]
