# Generated by Django 3.1.3 on 2020-11-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBSE', '0024_demand_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='stock_id',
            field=models.IntegerField(),
        ),
    ]
