# Generated by Django 3.1.3 on 2020-11-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookBSE', '0025_auto_20201123_2005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
    ]
