# Generated by Django 3.1.3 on 2020-11-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBSE', '0026_auto_20201124_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
