# Generated by Django 3.1.3 on 2020-11-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookBSE', '0027_stock_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='bookId',
            field=models.IntegerField(default=0),
        ),
    ]
