# Generated by Django 3.1.3 on 2020-11-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookBSE', '0028_demand_bookid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportproblem',
            unique_together=set(),
        ),
    ]
