# Generated by Django 3.1.3 on 2020-12-01 00:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0003_auto_20201130_2029'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serve',
            unique_together={('food', 'seller', 'start_serve_time', 'end_serve_time', 'date')},
        ),
    ]
