# Generated by Django 3.1.3 on 2020-12-01 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20201201_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serve',
            name='date',
            field=models.DateField(default=datetime.date),
        ),
    ]
