# Generated by Django 3.1.3 on 2020-12-01 16:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20201201_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serve',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 1, 16, 12, 28, 379943, tzinfo=utc)),
        ),
    ]
