# Generated by Django 3.1.3 on 2020-12-01 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20201201_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serve',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
